/*
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.8-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.api;

import net.leanix.api.common.ApiException;
import net.leanix.api.models.FactSheetArchiveParameter;
import net.leanix.api.models.FactSheetDataREST;
import net.leanix.api.models.FactSheetListResponse;
import net.leanix.api.models.FactSheetResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FactsheetsApi
 */
@Ignore
public class FactsheetsApiTest {

    private final FactsheetsApi api = new FactsheetsApi();

    
    /**
     * archiveFactSheet
     *
     * Archives a Fact Sheet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void archiveFactSheetTest() throws ApiException {
        String id = null;
        FactSheetArchiveParameter body = null;
        FactSheetListResponse response = api.archiveFactSheet(id, body);

        // TODO: test validations
    }
    
    /**
     * getFactSheet
     *
     * Retrieves a Fact Sheet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFactSheetTest() throws ApiException {
        String id = null;
        String relationTypes = null;
        FactSheetResponse response = api.getFactSheet(id, relationTypes);

        // TODO: test validations
    }
    
    /**
     * getFactSheets
     *
     * Retrieves all Fact Sheets
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFactSheetsTest() throws ApiException {
        String type = null;
        String fetchRelations = null;
        FactSheetListResponse response = api.getFactSheets(type, fetchRelations);

        // TODO: test validations
    }
    
    /**
     * createFactSheet
     *
     * Creates a Fact Sheet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postFactSheetTest() throws ApiException {
        FactSheetDataREST body = null;
        FactSheetListResponse response = api.postFactSheet(body);

        // TODO: test validations
    }
    
    /**
     * updateFactSheet
     *
     * Updates a Fact Sheet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putFactSheetTest() throws ApiException {
        String id = null;
        FactSheetDataREST body = null;
        FactSheetListResponse response = api.putFactSheet(id, body);

        // TODO: test validations
    }
    
}
