/*
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.13-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.api;

import net.leanix.api.common.ApiException;
import net.leanix.api.models.ExcelExportResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ImportsApi
 */
@Ignore
public class ImportsApiTest {

    private final ImportsApi api = new ImportsApi();

    
    /**
     * importExcelFile
     *
     * Imports the Fact Sheet data in the given Excel file
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void importExcelFileTest() throws ApiException {
        ExcelExportResponse response = api.importExcelFile();

        // TODO: test validations
    }
    
}
