/**
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.8-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package net.leanix.api;

import net.leanix.api.common.ApiException;
import net.leanix.api.models.ExcelExportResponse;
import org.junit.Test;


/**
 * API tests for ImportsApi
 */
public class ImportsApiTest {

    private final ImportsApi api = new ImportsApi();

    
    /**
     * importExcelFile
     *
     * Imports the Fact Sheet data in the given Excel file
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void importExcelFileTest() throws ApiException {
        // ExcelExportResponse response = api.importExcelFile();

        // TODO: test validations
    }
    
}
