/*
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.8-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.api;

import net.leanix.api.common.ApiException;
import net.leanix.api.models.Relation;
import net.leanix.api.models.RelationResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RelationsApi
 */
@Ignore
public class RelationsApiTest {

    private final RelationsApi api = new RelationsApi();

    
    /**
     * createRelation
     *
     * Creates the given relation. When adding constraining relations only the ID of these relations will be used.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRelationTest() throws ApiException {
        Relation relation = null;
        RelationResponse response = api.createRelation(relation);

        // TODO: test validations
    }
    
    /**
     * deleteRelation
     *
     * Deletes the given relation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteRelationTest() throws ApiException {
        String id = null;
        api.deleteRelation(id);

        // TODO: test validations
    }
    
    /**
     * updateRelation
     *
     * Updates the given relation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateRelationTest() throws ApiException {
        String id = null;
        Relation relation = null;
        RelationResponse response = api.updateRelation(id, relation);

        // TODO: test validations
    }
    
}
