/*
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
<<<<<<< HEAD
 * OpenAPI spec version: 5.0.174
 *
=======
 * OpenAPI spec version: 5.0.396
 * 
>>>>>>> release/3.9.30
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.api;

import net.leanix.api.common.ApiException;
import net.leanix.api.models.SuggestionsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SuggestionsApi
 */
@Ignore
public class SuggestionsApiTest {

    private final SuggestionsApi api = new SuggestionsApi();

    
    /**
     * getSuggestions
     *
     * Retrieves a list of suggestions for a search term
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSuggestionsTest() throws ApiException {
        String q = null;
        String object = null;
        Integer count = null;
        Boolean perType = null;
        SuggestionsResponse response = api.getSuggestions(q, object, count, perType);

        // TODO: test validations
    }
    
}
