/*
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 3.9.140-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.api;

import net.leanix.api.common.ApiException;
import net.leanix.api.models.Todo;
import net.leanix.api.models.TodoListResponse;
import net.leanix.api.models.TodoResponse;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TodosApi
 */
@Ignore
public class TodosApiTest {

    private final TodosApi api = new TodosApi();

    
    /**
     * createTodo
     *
     * Saves a todo in the database
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTodoTest() throws ApiException {
        Todo body = null;
        UUID workspaceId = null;
        TodoResponse response = api.createTodo(body, workspaceId);

        // TODO: test validations
    }
    
    /**
     * deleteTodo
     *
     * deletes a todo item based on provided id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTodoTest() throws ApiException {
        UUID id = null;
        UUID workspaceId = null;
        api.deleteTodo(id, workspaceId);

        // TODO: test validations
    }
    
    /**
     * getTodo
     *
     * Retrieves a todo by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTodoTest() throws ApiException {
        UUID id = null;
        TodoResponse response = api.getTodo(id);

        // TODO: test validations
    }
    
    /**
     * getTodos
     *
     * Retrieves all todos a user can read.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTodosTest() throws ApiException {
        String type = null;
        String status = null;
        UUID factSheetId = null;
        UUID userId = null;
        UUID workspaceId = null;
        TodoListResponse response = api.getTodos(type, status, factSheetId, userId, workspaceId);

        // TODO: test validations
    }
    
    /**
     * updateTodo
     *
     * Updates a todo stored in the database.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTodoTest() throws ApiException {
        UUID id = null;
        UUID workspaceId = null;
        Todo body = null;
        TodoResponse response = api.updateTodo(id, workspaceId, body);

        // TODO: test validations
    }
    
}
