/*
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 3.9.139-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.api.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import net.leanix.api.models.AggregationPath;
import net.leanix.api.models.DataType;

/**
 * AggregatedDataType
 */

public class AggregatedDataType extends DataType {
  @JsonProperty("paths")
  private List<AggregationPath> paths = new ArrayList<AggregationPath>();

  /**
   * Gets or Sets function
   */
  public enum FunctionEnum {
    SUM("SUM"),
    
    AVG("AVG"),
    
    MIN("MIN"),
    
    MAX("MAX"),
    
    COUNT("COUNT");

    private String value;

    FunctionEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FunctionEnum fromValue(String text) {
      for (FunctionEnum b : FunctionEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("function")
  private FunctionEnum function = null;

  public AggregatedDataType paths(List<AggregationPath> paths) {
    this.paths = paths;
    return this;
  }

  public AggregatedDataType addPathsItem(AggregationPath pathsItem) {
    this.paths.add(pathsItem);
    return this;
  }

   /**
   * Get paths
   * @return paths
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AggregationPath> getPaths() {
    return paths;
  }

  public void setPaths(List<AggregationPath> paths) {
    this.paths = paths;
  }

  public AggregatedDataType function(FunctionEnum function) {
    this.function = function;
    return this;
  }

   /**
   * Get function
   * @return function
  **/
  @ApiModelProperty(example = "null", value = "")
  public FunctionEnum getFunction() {
    return function;
  }

  public void setFunction(FunctionEnum function) {
    this.function = function;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AggregatedDataType aggregatedDataType = (AggregatedDataType) o;
    return Objects.equals(this.paths, aggregatedDataType.paths) &&
        Objects.equals(this.function, aggregatedDataType.function) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paths, function, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AggregatedDataType {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    paths: ").append(toIndentedString(paths)).append("\n");
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

