/*
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 5.0.174
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.api.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * BookmarkSuggestionsResponse
 */

public class BookmarkSuggestionsResponse {
  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    OK("OK"),
    
    ERROR("ERROR");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("data")
  private List<BookmarkSuggestion> data = new ArrayList<BookmarkSuggestion>();

  @JsonProperty("errorMessage")
  private String errorMessage = null;

  @JsonProperty("errors")
  private List<ApiError> errors = new ArrayList<ApiError>();

  @JsonProperty("total")
  private Integer total = null;

  @JsonProperty("pageCursorValues")
  private List<String> pageCursorValues = new ArrayList<String>();

  public BookmarkSuggestionsResponse status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public BookmarkSuggestionsResponse type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public BookmarkSuggestionsResponse data(List<BookmarkSuggestion> data) {
    this.data = data;
    return this;
  }

  public BookmarkSuggestionsResponse addDataItem(BookmarkSuggestion dataItem) {
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<BookmarkSuggestion> getData() {
    return data;
  }

  public void setData(List<BookmarkSuggestion> data) {
    this.data = data;
  }

  public BookmarkSuggestionsResponse errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Get errorMessage
   * @return errorMessage
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  public BookmarkSuggestionsResponse errors(List<ApiError> errors) {
    this.errors = errors;
    return this;
  }

  public BookmarkSuggestionsResponse addErrorsItem(ApiError errorsItem) {
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ApiError> getErrors() {
    return errors;
  }

  public void setErrors(List<ApiError> errors) {
    this.errors = errors;
  }

  public BookmarkSuggestionsResponse total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }

  public BookmarkSuggestionsResponse pageCursorValues(List<String> pageCursorValues) {
    this.pageCursorValues = pageCursorValues;
    return this;
  }

  public BookmarkSuggestionsResponse addPageCursorValuesItem(String pageCursorValuesItem) {
    this.pageCursorValues.add(pageCursorValuesItem);
    return this;
  }

   /**
   * Get pageCursorValues
   * @return pageCursorValues
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getPageCursorValues() {
    return pageCursorValues;
  }

  public void setPageCursorValues(List<String> pageCursorValues) {
    this.pageCursorValues = pageCursorValues;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookmarkSuggestionsResponse bookmarkSuggestionsResponse = (BookmarkSuggestionsResponse) o;
    return Objects.equals(this.status, bookmarkSuggestionsResponse.status) &&
        Objects.equals(this.type, bookmarkSuggestionsResponse.type) &&
        Objects.equals(this.data, bookmarkSuggestionsResponse.data) &&
        Objects.equals(this.errorMessage, bookmarkSuggestionsResponse.errorMessage) &&
        Objects.equals(this.errors, bookmarkSuggestionsResponse.errors) &&
        Objects.equals(this.total, bookmarkSuggestionsResponse.total) &&
        Objects.equals(this.pageCursorValues, bookmarkSuggestionsResponse.pageCursorValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, type, data, errorMessage, errors, total, pageCursorValues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookmarkSuggestionsResponse {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    pageCursorValues: ").append(toIndentedString(pageCursorValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

