/*
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 5.0.174
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.api.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * CustomizationConfig
 */

public class CustomizationConfig {
  @JsonProperty("maxHierarchyLevel")
  private Integer maxHierarchyLevel = null;

  @JsonProperty("qualitySeal")
  private CustomizationQualitySeal qualitySeal = null;

  /**
   * Gets or Sets defaultACL
   */
  public enum DefaultACLEnum {
    GLOBAL("GLOBAL"),
    
    WRITE_RESTRICTED("WRITE_RESTRICTED"),
    
    READ_RESTRICTED("READ_RESTRICTED");

    private String value;

    DefaultACLEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DefaultACLEnum fromValue(String text) {
      for (DefaultACLEnum b : DefaultACLEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("defaultACL")
  private DefaultACLEnum defaultACL = null;

  public CustomizationConfig maxHierarchyLevel(Integer maxHierarchyLevel) {
    this.maxHierarchyLevel = maxHierarchyLevel;
    return this;
  }

   /**
   * Get maxHierarchyLevel
   * @return maxHierarchyLevel
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getMaxHierarchyLevel() {
    return maxHierarchyLevel;
  }

  public void setMaxHierarchyLevel(Integer maxHierarchyLevel) {
    this.maxHierarchyLevel = maxHierarchyLevel;
  }

  public CustomizationConfig qualitySeal(CustomizationQualitySeal qualitySeal) {
    this.qualitySeal = qualitySeal;
    return this;
  }

   /**
   * Get qualitySeal
   * @return qualitySeal
  **/
  @ApiModelProperty(example = "null", value = "")
  public CustomizationQualitySeal getQualitySeal() {
    return qualitySeal;
  }

  public void setQualitySeal(CustomizationQualitySeal qualitySeal) {
    this.qualitySeal = qualitySeal;
  }

  public CustomizationConfig defaultACL(DefaultACLEnum defaultACL) {
    this.defaultACL = defaultACL;
    return this;
  }

   /**
   * Get defaultACL
   * @return defaultACL
  **/
  @ApiModelProperty(example = "null", value = "")
  public DefaultACLEnum getDefaultACL() {
    return defaultACL;
  }

  public void setDefaultACL(DefaultACLEnum defaultACL) {
    this.defaultACL = defaultACL;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomizationConfig customizationConfig = (CustomizationConfig) o;
    return Objects.equals(this.maxHierarchyLevel, customizationConfig.maxHierarchyLevel) &&
        Objects.equals(this.qualitySeal, customizationConfig.qualitySeal) &&
        Objects.equals(this.defaultACL, customizationConfig.defaultACL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxHierarchyLevel, qualitySeal, defaultACL);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomizationConfig {\n");
    
    sb.append("    maxHierarchyLevel: ").append(toIndentedString(maxHierarchyLevel)).append("\n");
    sb.append("    qualitySeal: ").append(toIndentedString(qualitySeal)).append("\n");
    sb.append("    defaultACL: ").append(toIndentedString(defaultACL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

