/*
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 3.9.22-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.api.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.leanix.api.models.CustomValidator;
import net.leanix.api.models.ExternalIdFieldDefinition;
import net.leanix.api.models.FactSheetDefinition;
import net.leanix.api.models.RelationDefinition;
import net.leanix.api.models.RulesDefinition;

/**
 * DataModel
 */

public class DataModel {
  @JsonProperty("factSheets")
  private Map<String, FactSheetDefinition> factSheets = new HashMap<String, FactSheetDefinition>();

  @JsonProperty("relations")
  private Map<String, RelationDefinition> relations = new HashMap<String, RelationDefinition>();

  @JsonProperty("validators")
  private Map<String, CustomValidator> validators = new HashMap<String, CustomValidator>();

  @JsonProperty("externalIdFields")
  private Map<String, ExternalIdFieldDefinition> externalIdFields = new HashMap<String, ExternalIdFieldDefinition>();

  @JsonProperty("rules")
  private RulesDefinition rules = null;

  public DataModel factSheets(Map<String, FactSheetDefinition> factSheets) {
    this.factSheets = factSheets;
    return this;
  }

  public DataModel putFactSheetsItem(String key, FactSheetDefinition factSheetsItem) {
    this.factSheets.put(key, factSheetsItem);
    return this;
  }

   /**
   * Get factSheets
   * @return factSheets
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, FactSheetDefinition> getFactSheets() {
    return factSheets;
  }

  public void setFactSheets(Map<String, FactSheetDefinition> factSheets) {
    this.factSheets = factSheets;
  }

  public DataModel relations(Map<String, RelationDefinition> relations) {
    this.relations = relations;
    return this;
  }

  public DataModel putRelationsItem(String key, RelationDefinition relationsItem) {
    this.relations.put(key, relationsItem);
    return this;
  }

   /**
   * Get relations
   * @return relations
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, RelationDefinition> getRelations() {
    return relations;
  }

  public void setRelations(Map<String, RelationDefinition> relations) {
    this.relations = relations;
  }

  public DataModel validators(Map<String, CustomValidator> validators) {
    this.validators = validators;
    return this;
  }

  public DataModel putValidatorsItem(String key, CustomValidator validatorsItem) {
    this.validators.put(key, validatorsItem);
    return this;
  }

   /**
   * Get validators
   * @return validators
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, CustomValidator> getValidators() {
    return validators;
  }

  public void setValidators(Map<String, CustomValidator> validators) {
    this.validators = validators;
  }

  public DataModel externalIdFields(Map<String, ExternalIdFieldDefinition> externalIdFields) {
    this.externalIdFields = externalIdFields;
    return this;
  }

  public DataModel putExternalIdFieldsItem(String key, ExternalIdFieldDefinition externalIdFieldsItem) {
    this.externalIdFields.put(key, externalIdFieldsItem);
    return this;
  }

   /**
   * Get externalIdFields
   * @return externalIdFields
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, ExternalIdFieldDefinition> getExternalIdFields() {
    return externalIdFields;
  }

  public void setExternalIdFields(Map<String, ExternalIdFieldDefinition> externalIdFields) {
    this.externalIdFields = externalIdFields;
  }

  public DataModel rules(RulesDefinition rules) {
    this.rules = rules;
    return this;
  }

   /**
   * Get rules
   * @return rules
  **/
  @ApiModelProperty(example = "null", value = "")
  public RulesDefinition getRules() {
    return rules;
  }

  public void setRules(RulesDefinition rules) {
    this.rules = rules;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataModel dataModel = (DataModel) o;
    return Objects.equals(this.factSheets, dataModel.factSheets) &&
        Objects.equals(this.relations, dataModel.relations) &&
        Objects.equals(this.validators, dataModel.validators) &&
        Objects.equals(this.externalIdFields, dataModel.externalIdFields) &&
        Objects.equals(this.rules, dataModel.rules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(factSheets, relations, validators, externalIdFields, rules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataModel {\n");
    
    sb.append("    factSheets: ").append(toIndentedString(factSheets)).append("\n");
    sb.append("    relations: ").append(toIndentedString(relations)).append("\n");
    sb.append("    validators: ").append(toIndentedString(validators)).append("\n");
    sb.append("    externalIdFields: ").append(toIndentedString(externalIdFields)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

