/*
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 5.0.396
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.api.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import net.leanix.api.models.DeleteItemActionPayload;
import net.leanix.api.models.MetaModelActionInputObject;
import net.leanix.api.models.StructuredNode;

/**
 * DeleteItemActionInput
 */

public class DeleteItemActionInput extends MetaModelActionInputObject {
  @JsonProperty("payload")
  private DeleteItemActionPayload payload = null;

  public DeleteItemActionInput payload(DeleteItemActionPayload payload) {
    this.payload = payload;
    return this;
  }

   /**
   * Get payload
   * @return payload
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DeleteItemActionPayload getPayload() {
    return payload;
  }

  public void setPayload(DeleteItemActionPayload payload) {
    this.payload = payload;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteItemActionInput deleteItemActionInput = (DeleteItemActionInput) o;
    return Objects.equals(this.payload, deleteItemActionInput.payload) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payload, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteItemActionInput {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

