/*
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 5.0.174
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.api.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * FactSheet
 */

public class FactSheet {
  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("displayName")
  private String displayName = null;

  @JsonProperty("fullName")
  private String fullName = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("tags")
  private List<Tag> tags = new ArrayList<Tag>();

  @JsonProperty("fields")
  private List<FieldnameAndData> fields = new ArrayList<FieldnameAndData>();

  @JsonProperty("relations")
  private List<FactSheetRelation> relations = new ArrayList<FactSheetRelation>();

  @JsonProperty("completion")
  private Completion completion = null;

  @JsonProperty("createdAt")
  private OffsetDateTime createdAt = null;

  @JsonProperty("updatedAt")
  private OffsetDateTime updatedAt = null;

  @JsonProperty("documents")
  private List<Document> documents = new ArrayList<Document>();

  @JsonProperty("approvedAt")
  private OffsetDateTime approvedAt = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    
    ARCHIVED("ARCHIVED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("permittedReadACL")
  private List<AccessControlEntityReference> permittedReadACL = new ArrayList<AccessControlEntityReference>();

  @JsonProperty("permittedWriteACL")
  private List<AccessControlEntityReference> permittedWriteACL = new ArrayList<AccessControlEntityReference>();

  @JsonProperty("qualitySealStatus")
  private QualitySealStatusEnum qualitySealStatus = null;
  @JsonProperty("score")
  private Float score = null;
  @JsonProperty("permissions")
  private PermissionsField permissions = null;
  @JsonProperty("level")
  private Integer level = null;
  @JsonProperty("rev")
  private Long rev = null;
  @JsonProperty("naFields")
  private List<String> naFields = new ArrayList<String>();
  @JsonProperty("subscriptions")
  private List<Subscription> subscriptions = new ArrayList<Subscription>();

  /**
   * Get qualitySealStatus
   * @return qualitySealStatus
   **/
  @ApiModelProperty(example = "null", value = "")
  public QualitySealStatusEnum getQualitySealStatus() {
    return qualitySealStatus;
  }

  public FactSheet id(UUID id) {
    this.id = id;
    return this;
  }

  public void setQualitySealStatus(QualitySealStatusEnum qualitySealStatus) {
    this.qualitySealStatus = qualitySealStatus;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public FactSheet name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FactSheet description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public FactSheet displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public FactSheet fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Get fullName
   * @return fullName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public FactSheet type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public FactSheet tags(List<Tag> tags) {
    this.tags = tags;
    return this;
  }

  public FactSheet addTagsItem(Tag tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Tag> getTags() {
    return tags;
  }

  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }

  public FactSheet fields(List<FieldnameAndData> fields) {
    this.fields = fields;
    return this;
  }

  public FactSheet addFieldsItem(FieldnameAndData fieldsItem) {
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<FieldnameAndData> getFields() {
    return fields;
  }

  public void setFields(List<FieldnameAndData> fields) {
    this.fields = fields;
  }

  public FactSheet relations(List<FactSheetRelation> relations) {
    this.relations = relations;
    return this;
  }

  public FactSheet addRelationsItem(FactSheetRelation relationsItem) {
    this.relations.add(relationsItem);
    return this;
  }

   /**
   * Get relations
   * @return relations
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<FactSheetRelation> getRelations() {
    return relations;
  }

  public void setRelations(List<FactSheetRelation> relations) {
    this.relations = relations;
  }

  public FactSheet completion(Completion completion) {
    this.completion = completion;
    return this;
  }

   /**
   * Get completion
   * @return completion
  **/
  @ApiModelProperty(example = "null", value = "")
  public Completion getCompletion() {
    return completion;
  }

  public void setCompletion(Completion completion) {
    this.completion = completion;
  }

  public FactSheet createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public FactSheet updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(example = "null", value = "")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public FactSheet documents(List<Document> documents) {
    this.documents = documents;
    return this;
  }

  public FactSheet addDocumentsItem(Document documentsItem) {
    this.documents.add(documentsItem);
    return this;
  }

   /**
   * Get documents
   * @return documents
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Document> getDocuments() {
    return documents;
  }

  public void setDocuments(List<Document> documents) {
    this.documents = documents;
  }

  public FactSheet approvedAt(OffsetDateTime approvedAt) {
    this.approvedAt = approvedAt;
    return this;
  }

   /**
   * Get approvedAt
   * @return approvedAt
  **/
  @ApiModelProperty(example = "null", value = "")
  public OffsetDateTime getApprovedAt() {
    return approvedAt;
  }

  public void setApprovedAt(OffsetDateTime approvedAt) {
    this.approvedAt = approvedAt;
  }

  public FactSheet status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public FactSheet permittedReadACL(List<AccessControlEntityReference> permittedReadACL) {
    this.permittedReadACL = permittedReadACL;
    return this;
  }

  public FactSheet addPermittedReadACLItem(AccessControlEntityReference permittedReadACLItem) {
    this.permittedReadACL.add(permittedReadACLItem);
    return this;
  }

   /**
   * Get permittedReadACL
   * @return permittedReadACL
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AccessControlEntityReference> getPermittedReadACL() {
    return permittedReadACL;
  }

  public void setPermittedReadACL(List<AccessControlEntityReference> permittedReadACL) {
    this.permittedReadACL = permittedReadACL;
  }

  public FactSheet permittedWriteACL(List<AccessControlEntityReference> permittedWriteACL) {
    this.permittedWriteACL = permittedWriteACL;
    return this;
  }

  public FactSheet addPermittedWriteACLItem(AccessControlEntityReference permittedWriteACLItem) {
    this.permittedWriteACL.add(permittedWriteACLItem);
    return this;
  }

   /**
   * Get permittedWriteACL
   * @return permittedWriteACL
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AccessControlEntityReference> getPermittedWriteACL() {
    return permittedWriteACL;
  }

  public void setPermittedWriteACL(List<AccessControlEntityReference> permittedWriteACL) {
    this.permittedWriteACL = permittedWriteACL;
  }

  public FactSheet qualitySealStatus(QualitySealStatusEnum qualitySealStatus) {
    this.qualitySealStatus = qualitySealStatus;
    return this;
  }

  /**
   * Get id
   * @return id
   **/
  @ApiModelProperty(example = "null", value = "")
  public UUID getId() {
    return id;
  }

  public FactSheet score(Float score) {
    this.score = score;
    return this;
  }

  /**
   * Get score
   * @return score
   **/
  @ApiModelProperty(example = "null", value = "")
  public Float getScore() {
    return score;
  }

  public void setScore(Float score) {
    this.score = score;
  }

  public FactSheet permissions(PermissionsField permissions) {
    this.permissions = permissions;
    return this;
  }

  /**
   * Get permissions
   * @return permissions
   **/
  @ApiModelProperty(example = "null", value = "")
  public PermissionsField getPermissions() {
    return permissions;
  }

  public void setPermissions(PermissionsField permissions) {
    this.permissions = permissions;
  }

  public FactSheet level(Integer level) {
    this.level = level;
    return this;
  }

  /**
   * Get level
   * @return level
   **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLevel() {
    return level;
  }

  public void setLevel(Integer level) {
    this.level = level;
  }

  public FactSheet rev(Long rev) {
    this.rev = rev;
    return this;
  }

  /**
   * Get rev
   * @return rev
   **/
  @ApiModelProperty(example = "null", value = "")
  public Long getRev() {
    return rev;
  }

  public void setRev(Long rev) {
    this.rev = rev;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FactSheet factSheet = (FactSheet) o;
    return Objects.equals(this.id, factSheet.id) &&
        Objects.equals(this.name, factSheet.name) &&
        Objects.equals(this.description, factSheet.description) &&
        Objects.equals(this.displayName, factSheet.displayName) &&
        Objects.equals(this.fullName, factSheet.fullName) &&
        Objects.equals(this.type, factSheet.type) &&
        Objects.equals(this.tags, factSheet.tags) &&
        Objects.equals(this.fields, factSheet.fields) &&
        Objects.equals(this.relations, factSheet.relations) &&
        Objects.equals(this.completion, factSheet.completion) &&
        Objects.equals(this.createdAt, factSheet.createdAt) &&
        Objects.equals(this.updatedAt, factSheet.updatedAt) &&
        Objects.equals(this.documents, factSheet.documents) &&
        Objects.equals(this.approvedAt, factSheet.approvedAt) &&
        Objects.equals(this.status, factSheet.status) &&
        Objects.equals(this.permittedReadACL, factSheet.permittedReadACL) &&
        Objects.equals(this.permittedWriteACL, factSheet.permittedWriteACL) &&
        Objects.equals(this.qualitySealStatus, factSheet.qualitySealStatus) &&
        Objects.equals(this.score, factSheet.score) &&
        Objects.equals(this.permissions, factSheet.permissions) &&
        Objects.equals(this.level, factSheet.level) &&
        Objects.equals(this.rev, factSheet.rev) &&
        Objects.equals(this.naFields, factSheet.naFields) &&
        Objects.equals(this.subscriptions, factSheet.subscriptions);
  }

  public FactSheet naFields(List<String> naFields) {
    this.naFields = naFields;
    return this;
  }

  public FactSheet addNaFieldsItem(String naFieldsItem) {
    this.naFields.add(naFieldsItem);
    return this;
  }

  /**
   * Get naFields
   * @return naFields
   **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getNaFields() {
    return naFields;
  }

  public void setNaFields(List<String> naFields) {
    this.naFields = naFields;
  }

  public FactSheet subscriptions(List<Subscription> subscriptions) {
    this.subscriptions = subscriptions;
    return this;
  }

  public FactSheet addSubscriptionsItem(Subscription subscriptionsItem) {
    this.subscriptions.add(subscriptionsItem);
    return this;
  }

  /**
   * Get subscriptions
   * @return subscriptions
   **/
  @ApiModelProperty(example = "null", value = "")
  public List<Subscription> getSubscriptions() {
    return subscriptions;
  }

  public void setSubscriptions(List<Subscription> subscriptions) {
    this.subscriptions = subscriptions;
  }

  @Override
  public int hashCode() {
    return Objects
        .hash(id, name, description, displayName, fullName, type, tags, fields, relations, completion, createdAt, updatedAt,
            documents, approvedAt, status, permittedReadACL, permittedWriteACL, qualitySealStatus, score, permissions, level, rev,
            naFields, subscriptions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FactSheet {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    relations: ").append(toIndentedString(relations)).append("\n");
    sb.append("    completion: ").append(toIndentedString(completion)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("    approvedAt: ").append(toIndentedString(approvedAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    permittedReadACL: ").append(toIndentedString(permittedReadACL)).append("\n");
    sb.append("    permittedWriteACL: ").append(toIndentedString(permittedWriteACL)).append("\n");
    sb.append("    qualitySealStatus: ").append(toIndentedString(qualitySealStatus)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    rev: ").append(toIndentedString(rev)).append("\n");
    sb.append("    naFields: ").append(toIndentedString(naFields)).append("\n");
    sb.append("    subscriptions: ").append(toIndentedString(subscriptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }


  /**
   * Gets or Sets qualitySealStatus
   */
  public enum QualitySealStatusEnum {
    DISABLED("DISABLED"),

    APPROVED("APPROVED"),

    BROKEN("BROKEN");

    private String value;

    QualitySealStatusEnum(String value) {
      this.value = value;
    }

    @JsonCreator
    public static QualitySealStatusEnum fromValue(String text) {
      for (QualitySealStatusEnum b : QualitySealStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

