/*
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 5.0.170
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.api.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * FactSheetLabelTranslation
 */

public class FactSheetLabelTranslation {
  @JsonProperty("plural")
  private String plural = null;

  @JsonProperty("singular")
  private String singular = null;

  public FactSheetLabelTranslation plural(String plural) {
    this.plural = plural;
    return this;
  }

   /**
   * Get plural
   * @return plural
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPlural() {
    return plural;
  }

  public void setPlural(String plural) {
    this.plural = plural;
  }

  public FactSheetLabelTranslation singular(String singular) {
    this.singular = singular;
    return this;
  }

   /**
   * Get singular
   * @return singular
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSingular() {
    return singular;
  }

  public void setSingular(String singular) {
    this.singular = singular;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FactSheetLabelTranslation factSheetLabelTranslation = (FactSheetLabelTranslation) o;
    return Objects.equals(this.plural, factSheetLabelTranslation.plural) &&
        Objects.equals(this.singular, factSheetLabelTranslation.singular);
  }

  @Override
  public int hashCode() {
    return Objects.hash(plural, singular);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FactSheetLabelTranslation {\n");
    
    sb.append("    plural: ").append(toIndentedString(plural)).append("\n");
    sb.append("    singular: ").append(toIndentedString(singular)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

