/*
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
<<<<<<< HEAD
 * OpenAPI spec version: 5.0.174
 *
=======
 * OpenAPI spec version: 5.0.396
 * 
>>>>>>> release/3.9.30
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.api.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import net.leanix.api.models.ApiError;
import net.leanix.api.models.FactSheetResourceModelDefinition;

/**
 * FactSheetResourceModelResponse
 */

public class FactSheetResourceModelResponse {
<<<<<<< HEAD

=======
>>>>>>> release/3.9.30
  @JsonProperty("status")
  private String status = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("errors")
  private List<ApiError> errors = new ArrayList<ApiError>();

  @JsonProperty("total")
  private Long total = null;

  @JsonProperty("data")
  private FactSheetResourceModelDefinition data = null;

  public FactSheetResourceModelResponse status(String status) {
    this.status = status;
    return this;
  }

<<<<<<< HEAD
  /**
   * Get status
   * @return status
   **/
=======
   /**
   * Get status
   * @return status
  **/
>>>>>>> release/3.9.30
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public FactSheetResourceModelResponse type(String type) {
    this.type = type;
    return this;
  }

<<<<<<< HEAD
  /**
   * Get type
   * @return type
   **/
=======
   /**
   * Get type
   * @return type
  **/
>>>>>>> release/3.9.30
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public FactSheetResourceModelResponse message(String message) {
    this.message = message;
    return this;
  }

<<<<<<< HEAD
  /**
   * Get message
   * @return message
   **/
=======
   /**
   * Get message
   * @return message
  **/
>>>>>>> release/3.9.30
  @ApiModelProperty(example = "null", value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public FactSheetResourceModelResponse errors(List<ApiError> errors) {
    this.errors = errors;
    return this;
  }

  public FactSheetResourceModelResponse addErrorsItem(ApiError errorsItem) {
    this.errors.add(errorsItem);
    return this;
  }

<<<<<<< HEAD
  /**
   * Get errors
   * @return errors
   **/
=======
   /**
   * Get errors
   * @return errors
  **/
>>>>>>> release/3.9.30
  @ApiModelProperty(example = "null", value = "")
  public List<ApiError> getErrors() {
    return errors;
  }

  public void setErrors(List<ApiError> errors) {
    this.errors = errors;
  }

  public FactSheetResourceModelResponse total(Long total) {
    this.total = total;
    return this;
  }

<<<<<<< HEAD
  /**
   * Get total
   * @return total
   **/
=======
   /**
   * Get total
   * @return total
  **/
>>>>>>> release/3.9.30
  @ApiModelProperty(example = "null", value = "")
  public Long getTotal() {
    return total;
  }

  public void setTotal(Long total) {
    this.total = total;
  }

  public FactSheetResourceModelResponse data(FactSheetResourceModelDefinition data) {
    this.data = data;
    return this;
  }

<<<<<<< HEAD
  /**
   * Get data
   * @return data
   **/
=======
   /**
   * Get data
   * @return data
  **/
>>>>>>> release/3.9.30
  @ApiModelProperty(example = "null", value = "")
  public FactSheetResourceModelDefinition getData() {
    return data;
  }

  public void setData(FactSheetResourceModelDefinition data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FactSheetResourceModelResponse factSheetResourceModelResponse = (FactSheetResourceModelResponse) o;
    return Objects.equals(this.status, factSheetResourceModelResponse.status) &&
        Objects.equals(this.type, factSheetResourceModelResponse.type) &&
        Objects.equals(this.message, factSheetResourceModelResponse.message) &&
        Objects.equals(this.errors, factSheetResourceModelResponse.errors) &&
        Objects.equals(this.total, factSheetResourceModelResponse.total) &&
        Objects.equals(this.data, factSheetResourceModelResponse.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, type, message, errors, total, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FactSheetResourceModelResponse {\n");
<<<<<<< HEAD

=======
    
>>>>>>> release/3.9.30
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
<<<<<<< HEAD

=======
  
>>>>>>> release/3.9.30
}

