/*
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 5.0.174
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.api.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;

/**
 * MetaModelActionData
 */

public class MetaModelActionData {

    @JsonProperty("id")
    private UUID id = null;
    @JsonProperty("type")
    private TypeEnum type = null;
    @JsonProperty("subType")
    private SubTypeEnum subType = null;
    @JsonProperty("node")
    private Object node = null;
    @JsonProperty("payload")
    private Object payload = null;
    @JsonProperty("oldValue")
    private Map<String, Object> oldValue = new HashMap<String, Object>();
    @JsonProperty("status")
    private StatusEnum status = null;
    @JsonProperty("error")
    private String error = null;
    @JsonProperty("createdAt")
    private Long createdAt = null;
    @JsonProperty("updatedAt")
    private Long updatedAt = null;

    /**
     * Get id
     * @return id
     **/
    @ApiModelProperty(example = "null", value = "")
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Get type
     * @return type
     **/
    @ApiModelProperty(example = "null", value = "")
    public TypeEnum getType() {
        return type;
    }

    public void setType(TypeEnum type) {
        this.type = type;
    }

    /**
     * Get subType
     * @return subType
     **/
    @ApiModelProperty(example = "null", value = "")
    public SubTypeEnum getSubType() {
        return subType;
    }

    public void setSubType(SubTypeEnum subType) {
        this.subType = subType;
    }

    public MetaModelActionData id(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Get node
     * @return node
     **/
    @ApiModelProperty(example = "null", value = "")
    public Object getNode() {
        return node;
    }

    public void setNode(Object node) {
        this.node = node;
    }

    public MetaModelActionData type(TypeEnum type) {
        this.type = type;
        return this;
    }

    /**
     * Get payload
     * @return payload
     **/
    @ApiModelProperty(example = "null", value = "")
    public Object getPayload() {
        return payload;
    }

    public void setPayload(Object payload) {
        this.payload = payload;
    }

    public MetaModelActionData subType(SubTypeEnum subType) {
        this.subType = subType;
        return this;
    }

    /**
     * Get oldValue
     * @return oldValue
     **/
    @ApiModelProperty(example = "null", value = "")
    public Map<String, Object> getOldValue() {
        return oldValue;
    }

    public void setOldValue(Map<String, Object> oldValue) {
        this.oldValue = oldValue;
    }

    public MetaModelActionData node(Object node) {
        this.node = node;
        return this;
    }

    /**
     * Get status
     * @return status
     **/
    @ApiModelProperty(example = "null", value = "")
    public StatusEnum getStatus() {
        return status;
    }

    public void setStatus(StatusEnum status) {
        this.status = status;
    }

    public MetaModelActionData payload(Object payload) {
        this.payload = payload;
        return this;
    }

    /**
     * Get error
     * @return error
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public MetaModelActionData oldValue(Map<String, Object> oldValue) {
        this.oldValue = oldValue;
        return this;
    }

    public MetaModelActionData putOldValueItem(String key, Object oldValueItem) {
        this.oldValue.put(key, oldValueItem);
        return this;
    }

    /**
     * Get createdAt
     * @return createdAt
     **/
    @ApiModelProperty(example = "null", value = "")
    public Long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    public MetaModelActionData status(StatusEnum status) {
        this.status = status;
        return this;
    }

    /**
     * Get updatedAt
     * @return updatedAt
     **/
    @ApiModelProperty(example = "null", value = "")
    public Long getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    public MetaModelActionData error(String error) {
        this.error = error;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MetaModelActionData {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    subType: ").append(toIndentedString(subType)).append("\n");
        sb.append("    node: ").append(toIndentedString(node)).append("\n");
        sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
        sb.append("    oldValue: ").append(toIndentedString(oldValue)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    error: ").append(toIndentedString(error)).append("\n");
        sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
        sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public MetaModelActionData createdAt(Long createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public MetaModelActionData updatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MetaModelActionData metaModelActionData = (MetaModelActionData) o;
        return Objects.equals(this.id, metaModelActionData.id) &&
            Objects.equals(this.type, metaModelActionData.type) &&
            Objects.equals(this.subType, metaModelActionData.subType) &&
            Objects.equals(this.node, metaModelActionData.node) &&
            Objects.equals(this.payload, metaModelActionData.payload) &&
            Objects.equals(this.oldValue, metaModelActionData.oldValue) &&
            Objects.equals(this.status, metaModelActionData.status) &&
            Objects.equals(this.error, metaModelActionData.error) &&
            Objects.equals(this.createdAt, metaModelActionData.createdAt) &&
            Objects.equals(this.updatedAt, metaModelActionData.updatedAt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, type, subType, node, payload, oldValue, status, error, createdAt, updatedAt);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Gets or Sets type
     */
    public enum TypeEnum {
        UPDATE_TRANSLATION("UPDATE_TRANSLATION"),

        CREATE_FIELD("CREATE_FIELD"),

        UPDATE_FIELD("UPDATE_FIELD"),

        MOVE_ITEM("MOVE_ITEM");

        private String value;

        TypeEnum(String value) {
            this.value = value;
        }

        @JsonCreator
        public static TypeEnum fromValue(String text) {
            for (TypeEnum b : TypeEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
    }


    /**
     * Gets or Sets subType
     */
    public enum SubTypeEnum {
        FACT_SHEET_TYPE("FACT_SHEET_TYPE"),

        SECTION("SECTION"),

        SUBSECTION_FIELD("SUBSECTION_FIELD"),

        SUBSECTION_RELATION("SUBSECTION_RELATION"),

        FIELD_FACT_SHEET("FIELD_FACT_SHEET"),

        FIELD_EXTERNAL_ID("FIELD_EXTERNAL_ID"),

        FIELD_RELATION("FIELD_RELATION"),

        FIELD_VALUE_FACT_SHEET("FIELD_VALUE_FACT_SHEET"),

    FIELD_VALUE_RELATION("FIELD_VALUE_RELATION"),

    VIEW_CONFIGURATION("VIEW_CONFIGURATION");

    private String value;

    SubTypeEnum(String value) {
      this.value = value;
    }

        @JsonCreator
        public static SubTypeEnum fromValue(String text) {
            for (SubTypeEnum b : SubTypeEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
    }

    /**
     * Gets or Sets status
     */
    public enum StatusEnum {
        PENDING("PENDING"),

        VALID("VALID"),

        INVALID("INVALID"),

        DONE("DONE");

        private String value;

        StatusEnum(String value) {
            this.value = value;
        }

        @JsonCreator
        public static StatusEnum fromValue(String text) {
            for (StatusEnum b : StatusEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
    }

}

