/*
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 4.0.48-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.api.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import net.leanix.api.models.FactSheetReference;

/**
 * RecommendationReference
 */

public class RecommendationReference {
  @JsonProperty("factSheetReference")
  private FactSheetReference factSheetReference = null;

  /**
   * Gets or Sets todoStatus
   */
  public enum TodoStatusEnum {
    OPEN("OPEN"),
    
    DISMISSED("DISMISSED"),
    
    DONE("DONE");

    private String value;

    TodoStatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TodoStatusEnum fromValue(String text) {
      for (TodoStatusEnum b : TodoStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("todoStatus")
  private TodoStatusEnum todoStatus = null;

  @JsonProperty("score")
  private Double score = null;

  public RecommendationReference factSheetReference(FactSheetReference factSheetReference) {
    this.factSheetReference = factSheetReference;
    return this;
  }

   /**
   * Get factSheetReference
   * @return factSheetReference
  **/
  @ApiModelProperty(example = "null", value = "")
  public FactSheetReference getFactSheetReference() {
    return factSheetReference;
  }

  public void setFactSheetReference(FactSheetReference factSheetReference) {
    this.factSheetReference = factSheetReference;
  }

  public RecommendationReference todoStatus(TodoStatusEnum todoStatus) {
    this.todoStatus = todoStatus;
    return this;
  }

   /**
   * Get todoStatus
   * @return todoStatus
  **/
  @ApiModelProperty(example = "null", value = "")
  public TodoStatusEnum getTodoStatus() {
    return todoStatus;
  }

  public void setTodoStatus(TodoStatusEnum todoStatus) {
    this.todoStatus = todoStatus;
  }

  public RecommendationReference score(Double score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getScore() {
    return score;
  }

  public void setScore(Double score) {
    this.score = score;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecommendationReference recommendationReference = (RecommendationReference) o;
    return Objects.equals(this.factSheetReference, recommendationReference.factSheetReference) &&
        Objects.equals(this.todoStatus, recommendationReference.todoStatus) &&
        Objects.equals(this.score, recommendationReference.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(factSheetReference, todoStatus, score);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecommendationReference {\n");
    
    sb.append("    factSheetReference: ").append(toIndentedString(factSheetReference)).append("\n");
    sb.append("    todoStatus: ").append(toIndentedString(todoStatus)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

