/*
 * LeanIX Pathfinder REST API
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 3.9.72-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.api.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import net.leanix.api.models.DataModelTranslation;
import net.leanix.api.models.ViewModelTranslation;

/**
 * Translation
 */

public class Translation {
  @JsonProperty("dataModel")
  private DataModelTranslation dataModel = null;

  @JsonProperty("viewModel")
  private ViewModelTranslation viewModel = null;

  public Translation dataModel(DataModelTranslation dataModel) {
    this.dataModel = dataModel;
    return this;
  }

   /**
   * Get dataModel
   * @return dataModel
  **/
  @ApiModelProperty(example = "null", value = "")
  public DataModelTranslation getDataModel() {
    return dataModel;
  }

  public void setDataModel(DataModelTranslation dataModel) {
    this.dataModel = dataModel;
  }

  public Translation viewModel(ViewModelTranslation viewModel) {
    this.viewModel = viewModel;
    return this;
  }

   /**
   * Get viewModel
   * @return viewModel
  **/
  @ApiModelProperty(example = "null", value = "")
  public ViewModelTranslation getViewModel() {
    return viewModel;
  }

  public void setViewModel(ViewModelTranslation viewModel) {
    this.viewModel = viewModel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Translation translation = (Translation) o;
    return Objects.equals(this.dataModel, translation.dataModel) &&
        Objects.equals(this.viewModel, translation.viewModel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataModel, viewModel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Translation {\n");
    
    sb.append("    dataModel: ").append(toIndentedString(dataModel)).append("\n");
    sb.append("    viewModel: ").append(toIndentedString(viewModel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

